# Study on the Quality of Websites Generated by Large Language Models (LLMs)

Thank you for your interest in my study on the quality of websites generated by large language models (LLMs).

On this page, you will find the participation conditions. Once you confirm that you agree with them, you will be asked to provide the link to your current academic website. The researcher will then verify that you meet the participation requirements and, if so, will send you access information for Lovable (a platform that generates websites through a chat-based interface), along with the task instructions and the survey.

The goal of this study is to better understand the value of generated websites through vibe coding tools, i.e. platforms that let you write in natural language and generate a ready-to-use website, from a user perspective.

This project is conducted by **Dr. Oriane Pierrès**, post-doctoral researcher at the University of Zurich (UZH) and is funded by the UZH Digital Society Initiative.

---

## Requirements to Participate

- Currently work as a researcher (from PhD candidate to Professor level)  
- Be based in Europe  
- Own a personal academic website (not the one provided by your university)  
- Perform the task in English  

---

## Study Process

The study includes 3 parts:

1. **Before starting the task**  
   You will be asked to indicate  
   - your current personal academic website, and  
   - how you created it.

2. **The task**  
   Generate a website with Lovable following a few instructions.

3. **Final survey**  
   To get your opinion on the website you generated.

The whole study is estimated to last about **30 to 60 minutes**.

Your participation is voluntary, and you may withdraw at any time.  
After withdrawal, the researcher keeps data for analysis. You may request data deletion.

---

## Data Collection and Management

As the study involves analysing personal academic websites, anonymity during data collection and analysis cannot be warranted. This means that the involved researcher will know during the analysis who fulfilled the task and the surveys.

However, during the website generation task, you will be asked to only provide information you would publish on your website openly.

In the survey, you will be asked to provide some background information that will serve to describe the sample and investigate underlying reasons that could influence your perception.

Non-anonymous data will be stored on the UZH OneDrive cloud until the end of the publication process. Aggregated and anonymous data will be stored for 5 years and may be used for further research extending upon this study. Non-anonymous data may be provided to reviewers in a publication process.

In the publication, no individual information will be shared without consent. At the end of the study, you will be asked if you want to enable the researcher to use screenshots of your website for illustrative purposes in the publication.

---

## Compensation

As a thank you for your participation, you will receive a **10 CHF Coop voucher** after filling out the final survey.

You may also keep the generated code after the end of the study.

---

## Contact Person

Should you have any questions at any time of the study, please contact:

**Dr. Oriane Pierrès**  
Email: [oriane.pierres@dsi.uzh.ch](mailto:oriane.pierres@dsi.uzh.ch)

